# Generated by Django 5.1.1 on 2025-02-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TRAINS', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('coach_class', models.CharField(max_length=20)),
                ('coach', models.CharField(max_length=50)),
                ('seat_type', models.CharField(max_length=5)),
                ('quota', models.CharField(max_length=50)),
                ('jan2', models.JSONField(null=True)),
                ('jan3', models.JSONField(null=True)),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatavail', to='TRAINS.traindata', to_field='trainNumber')),
            ],
        ),
    ]
