# Generated by Django 5.1.6 on 2025-02-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TRAINS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('coach_class', models.CharField(max_length=20)),
                ('coach', models.CharField(max_length=50)),
                ('seat_type', models.CharField(max_length=5)),
                ('quota', models.CharField(max_length=50)),
                ('feb6', models.JSONField(null=True)),
                ('feb7', models.JSONField(null=True)),
                ('feb8', models.JSONField(null=True)),
                ('feb9', models.JSONField(null=True)),
                ('jan6', models.JSONField(null=True)),
                ('feb10', models.JSONField(null=True)),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatavail', to='TRAINS.traindata', to_field='trainNumber')),
            ],
        ),
    ]
