# Generated by Django 5.1.6 on 2025-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEATAVAIL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatavaildb',
            name='Feb16',
        ),
        migrations.AddField(
            model_name='seatavaildb',
            name='Feb24',
            field=models.JSONField(null=True),
        ),
    ]
