# Generated by Django 5.1.1 on 2025-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEATAVAIL', '0002_seatavaildb_jan4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatavaildb',
            name='jan2',
        ),
        migrations.AddField(
            model_name='seatavaildb',
            name='jan5',
            field=models.JSONField(null=True),
        ),
    ]
